USE BDX
GO
DROP TABLE IF EXISTS dbo.BO_PARAMETROS_APIS_EXTERNAS
GO
CREATE TABLE dbo.BO_PARAMETROS_APIS_EXTERNAS
(
	ID BIGINT NOT NULL PRIMARY KEY,
	SISTEMA_O_PROCESO VARCHAR(50) NOT NULL,
	API_URL VARCHAR(255) NOT NULL,
	DESCRIPCION VARCHAR(70) DEFAULT(''),
	Activo Bit default(1),
	BASE_64_CREDENTIALS VARCHAR(MAX) DEFAULT ('')
)
