USE BDX
GO
DELETE FROM BO_PARAMETROS_APIS_EXTERNAS    
GO
INSERT INTO BO_PARAMETROS_APIS_EXTERNAS(ID,SISTEMA_O_PROCESO,API_URL, DESCRIPCION, Activo, BASE_64_CREDENTIALS)
VALUES
(1 /*IDENTIFICADOR PARA EL ENUM*/,'NOMBRE DEL PARAMETRO','http://www.api-del-servicio/api', 'DESCRIPCION', 1 /*ACTIVO O NO*/,'SI REQUIERE DE CREDENCIALES O ALGO ADICIONAL, VAN AQUI EN BASE64')