USE BDMaestros
GO
DROP PROCEDURE IF EXISTS dbo.BO_OBTENER_URL_PARAMETRO
GO
CREATE PROCEDURE dbo.BO_OBTENER_URL_PARAMETRO
@ID_PARAMETRO BIGINT
AS
BEGIN
	BEGIN TRY
		IF NOT EXISTS(SELECT 1 FROM BO_PARAMETROS_APIS_EXTERNAS WHERE ID = @ID_PARAMETRO)
			THROW 51000, 'EL ID DEL PARAMETRO NO EXISTE EN PARAMETROS BO', 1;

		SELECT ID, SISTEMA_O_PROCESO, API_URL, DESCRIPCION, Activo, BASE_64_CREDENTIALS
		FROM BO_PARAMETROS_APIS_EXTERNAS WHERE ID = @ID_PARAMETRO and Activo = 1
	END TRY
	BEGIN CATCH
		THROW;
	END CATCH	
END